In [1]:
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd

In [2]:
# loading_the iris dataset
iris = load_iris()

In [3]:
# training data 설정(잘못된 방법)
x_train = iris.data[:-30]
y_train = iris.target[: -30]
# test data 설정(잘못된 방법)
x_test = iris.data[-30:]
y_test = iris.target[-30:]

In [4]:
print(y_test) # training data와 test data의 분리가 잘 되지 않음.(2만 적음)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [5]:
from sklearn.ensemble import RandomForestClassifier

In [6]:
# n_estimators : Decision Tree의 개수(default=10)
# max_features : 최대 고려하는 feature의 개수(default=auto)
# oob_score : out-of-bag(OOB) 사용여부(default=False)
rfc = RandomForestClassifier(n_estimators=10)
rfc

RandomForestClassifier(n_estimators=10)

In [7]:
rfc.fit(x_train, y_train)
prediction = rfc.predict(x_test) # test data를 입력해 target data를 예측
print(prediction==y_test) # 예측 결과 precision 과 실제 test data의 target을 비교

[ True False  True False  True  True False False  True  True  True  True
  True False False  True  True  True False  True  True  True  True  True
  True  True  True  True  True  True]


In [8]:
# Random Forest 정확도 측정
rfc.score(x_test, y_test)

0.7666666666666667

In [9]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [10]:
print("Accuracy is :", accuracy_score(prediction, y_test))
print("===============================================")
print(classification_report(prediction, y_test))

Accuracy is : 0.7666666666666667
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         7
           2       0.77      1.00      0.87        23

    accuracy                           0.77        30
   macro avg       0.38      0.50      0.43        30
weighted avg       0.59      0.77      0.67        30



C:\Users\82104\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\82104\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\82104\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [11]:
from sklearn.model_selection import train_test_split
x = iris.data
y = iris.target
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size = 0.2)
print(y_test)
print(Y_test)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
[0 1 2 0 1 2 0 2 0 1 1 0 0 1 1 2 2 0 2 0 2 0 0 1 2 2 0 1 0 2]


In [12]:
clf = RandomForestClassifier(n_estimators=10)
clf.fit(X_train, Y_train)

RandomForestClassifier(n_estimators=10)

In [13]:
prediction_1 = clf.predict(X_test)

print("Accuracy is :", accuracy_score(prediction_1, Y_test))
print("===============================================")
print(classification_report(prediction_1, Y_test))

Accuracy is : 0.9666666666666667
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      0.89      0.94         9
           2       0.90      1.00      0.95         9

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.96        30
weighted avg       0.97      0.97      0.97        30



In [14]:
clf_2 = RandomForestClassifier(n_estimators=200,
                             max_features=4,
                             oob_score=True)
clf_2.fit(X_train, Y_train)
prediction_2 = clf_2.predict(X_test)

print("Accuracy is :", accuracy_score(prediction_2, Y_test))
print("===============================================")
print(classification_report(prediction_2, Y_test))

Accuracy is : 0.9333333333333333
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      0.80      0.89        10
           2       0.80      1.00      0.89         8

    accuracy                           0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.95      0.93      0.93        30



In [15]:
for feature, imp in zip(iris.feature_names, clf_2.feature_importances_):
    print(feature, imp) # petal width의 중요도가 가장 높음

sepal length (cm) 0.009577544014329538
sepal width (cm) 0.021260690041947503
petal length (cm) 0.3827128035514908
petal width (cm) 0.5864489623922321
